### PR TITLE
adds rust toolchain and cargo.lock file

### PR DESCRIPTION
**Pull request by Kade-Powell**

### CODE REVIEW

**Comment by gbj** [comment]
We've gone back and forth on this a few times but generally don't include lockfiles in the templates.

Adding the toolchain file is a good idea.

**Comment by Kade-Powell** [comment]
great, in that case i've added it to the .gitignore file.

**Comment by gbj** [comment]
Well, it's a little tricky: users of the template are generating a binary, and it's usually recommended to include `Cargo.lock` in your version control for a binary (but not for a library). So the preferred path here would be for this template not to have a lockfile (which is the status quo), and for cargo to generate the lockfile the first time you build it, which you would then commit the lockfile to your own binary. Adding it to `.gitignore` means that this won't happen automatically when you clone the template.

**Comment by Kade-Powell** [comment]
ah yeah, sorry about that. Multi-tasking strikes again. I updated once more, this should just encompass the change of adding rust-toolchain and removing the cargo.lock file i originally added.

**Comment by gbj** [comment]
Sounds great. Thanks so much.

**Pull request merged**
